[fira-sans-400]
family = "Fira Sans"
weight = 400
local = [
  "Fira Sans",
  "FiraSans-Regular",
]
remote.woff  = "https://fonts.gstatic.com/s/firasans/v5/EjsrzDkQUQCDwsBtLpcVQbO3LdcAZYWl9Si6vvxL-qU.woff"
remote.woff2 = "https://fonts.gstatic.com/s/firasans/v5/EjsrzDkQUQCDwsBtLpcVQZBw1xU1rKptJj_0jans920.woff2"


[fira-sans-500]
family = "Fira Sans"
weight = 500
local = [
  "Fira Sans Medium",
  "FiraSans-Medium",
]
remote.woff = "https://fonts.gstatic.com/s/firasans/v5/zM2u8V3CuPVwAAXFQcDi4KRDOzjiPcYnFooOUGCOsRk.woff"
remote.woff2 = "https://fonts.gstatic.com/s/firasans/v5/zM2u8V3CuPVwAAXFQcDi4Bampu5_7CjHW5spxoeN3Vs.woff2"


[fira-sans-700]
family = "Fira Sans"
weight = 700
local = [
  "Fira Sans Bold",
  "FiraSans-Bold",
]
remote.woff = "https://fonts.gstatic.com/s/firasans/v5/DugPdSljmOTocZOR2CItOqRDOzjiPcYnFooOUGCOsRk.woff"
remote.woff2 = "https://fonts.gstatic.com/s/firasans/v5/DugPdSljmOTocZOR2CItOhampu5_7CjHW5spxoeN3Vs.woff2"


[pt-sans]
family = "PT Sans"
weight = 400
local = [
  "PT Sans",
  "PTSans",
  "ptsans",
  "pt-sans",
]
remote.woff2 = "https://fonts.gstatic.com/s/ptsans/v17/jizaRExUiTo99u79D0yExdGM.woff2"
