name: demo

on:
  push:
    branches:
      - master

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make demo
      - run: make demo DEMO_FLAVOR=red
      - run: make demo DEMO_FLAVOR=blue
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/html
          publish_branch: html
